### ISSUE TITLE
AttributeError: module 'jinja2' has no attribute 'pass_context'

### ISSUE THREAD

**Issue by fjanoos** [wookayin/gpustat-web#18]
Hi
I first cloned the repo and then installed it using
`python setup.py install`

After that I tried to run it with 
`python -m gpustat_web --port 11001 hostname`

and I'm getting this error

```
Traceback (most recent call last):
  File "/lxhome/janoosfi/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/lxhome/janoosfi/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/apps/home/janoosfi/software/gpustat-web/gpustat_web/__main__.py", line 1, in <module>
    from .app import main
  File "/apps/home/janoosfi/software/gpustat-web/gpustat_web/app.py", line 26, in <module>
    import aiohttp_jinja2 as aiojinja2
  File "/lxhome/janoosfi/anaconda3/lib/python3.8/site-packages/aiohttp_jinja2-1.5-py3.8.egg/aiohttp_jinja2/__init__.py", line 29, in <module>
    from .helpers import GLOBAL_HELPERS
  File "/lxhome/janoosfi/anaconda3/lib/python3.8/site-packages/aiohttp_jinja2-1.5-py3.8.egg/aiohttp_jinja2/helpers.py", line 23, in <module>
    @jinja2.pass_context
AttributeError: module 'jinja2' has no attribute 'pass_context'
```

My python version 3.8.3

Please advise on how to resolve this.

**Comment by wookayin** [comment]
jinja2 3.1 has removed `jinja2.contextfunction` and renamed it to `jinja2.contextfunction`. The upstream library `aiohttp-jinja2` has catched up that change --- it is probably when `jinja2` is too old (< 3.0).

Try this:
```
pip install --upgrade aiohttp_jinja2
```

or
```
pip install --upgrade jinja2>=3.0
```

I will update dependencies to ensure this.

**Comment by AzyCrw4282** [comment]
> jinja2 3.1 has removed `jinja2.contextfunction` and renamed it to `jinja2.contextfunction`. The upstream library `aiohttp-jinja2` has catched up that change --- it is probably when `jinja2` is too old (< 3.0).

I think you meant to say `jinja2.pass_context` for the replacement in >= 3.0.0
