### ISSUE TITLE
Not working for py39

### ISSUE THREAD

**Issue by alekseyen** [wookayin/gpustat-web#20]
```
Traceback (most recent call last):
  File "/Users/alekseyen/miniconda3/envs/py39/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/alekseyen/miniconda3/envs/py39/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/alekseyen/miniconda3/envs/py39/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/alekseyen/PycharmProjects/efficient-dl-systems/gpustat-web/gpustat_web/__init__.py", line 3, in <module>
    import asyncssh
  File "/Users/alekseyen/miniconda3/envs/py39/lib/python3.9/site-packages/asyncssh/__init__.py", line 17, in <module>
    from .channel import SSHClientChannel, SSHServerChannel, SSHTCPChannel
  File "/Users/alekseyen/miniconda3/envs/py39/lib/python3.9/site-packages/asyncssh/channel.py", line 201
    asyncio.async(self._finish_open_request(session), loop=self._loop)
            ^
SyntaxError: invalid syntax
```

**Comment by alekseyen** [comment]
Guys can anyone share your requirements for make this staff working..

**Comment by wookayin** [comment]
@alekseyen This is definitely a problem of `asyncssh` not supporting python 3.9. This already seems to be resolved in the asyncssh library, so please update everything to date and try again. Let me know if it still doesn't work for you.
